



#PROBLEM STATEMENTS:
# Sales & Revenue Analysis
# 1 what is the revenue generated by each store location?
select sr.store_location, round(sum(sr.transaction_qty * sr.unit_price)) as 'Sales amount in GBP'
from sales_revenue sr
group by sr.store_location
order by 'Sales amount in GBP';

#2 Which product category has the highest total sales?
select product_category, round(sum(transaction_qty * unit_price)) as 'total sales'
from sales_revenue
group by product_category
order by 'total sales' desc;

#3 What are the top 5 best-selling products by quantity?
select 
	product_detail, 
	sum(transaction_qty) as total_quantity
from 
	sales_revenue
group by 
	product_detail
order by 
	sum(transaction_qty) desc
		limit 5;





/*💰 Pricing & Product Insights
4 What is the average unit price of products in each category?*/
select avg(unit_price) as 'Average Price', product_category
from sales_revenue
group by product_category
order by 'Averag Price';


#5 What is the total quantity sold per product type?
select product_type, sum(transaction_qty) as "Total qty sold"
from sales_revenue
group by product_type
order by sum(transaction_qty) desc;

select * from sales_revenue;

#6 What is the most popular product detail in each category?
select product_detail, product_category, sum(transaction_qty) as 'Total Quantity'
from sales_revenue
group by product_detail, product_category;

select * from sales_revenue;


#Time-Based Analysis
#7 How many transactions occurred each day?
select transaction_date, count(*) as 'Transaction Count'
from sales_revenue
group by transaction_date
order by transaction_date;



#8 Which hour of the day has the highest number of transactions?
select 
	case
		when transaction_time between '00:00:00' and '09:59:59' then "Between 12 AM to 10 AM"
		when transaction_time between '10:00:00' and '19:59:59' then "Between 10 AM to 8 PM"
		when transaction_time between '20:00:00' and '23:59:59' then "Between 8 PM to 12 AM"
	end as 'Time slot', 
    transaction_time, count(*) as "Transactions"
from sales_revenue
group by 'Time slot'
order by "Transactions" desc;

SELECT
    CASE
        WHEN transaction_time BETWEEN '00:00:00' AND '09:59:59' THEN 'Between 12 AM to 10 AM'
        WHEN transaction_time BETWEEN '10:00:00' AND '19:59:59' THEN 'Between 10 AM to 8 PM'
        WHEN transaction_time BETWEEN '20:00:00' AND '23:59:59' THEN 'Between 8 PM to 12 AM'
    END AS time_slot,
    COUNT(*) AS Transactions
FROM 
    sales_revenue
GROUP BY 
    time_slot
ORDER BY 
    Transactions DESC;

#9 What is the monthly revenue trend for each store location?
select * from sales_revenue;

select date_format(transaction_date,'%Y-%M') as Month, store_location,  round(sum(transaction_qty * unit_price), 3) as 'Total revenue'
from sales_revenue
group by date_format(transaction_date,'%Y-%M'), store_location
order by Month, 'Total revenue' desc;


# Store Performance
#10 What is the average transaction quantity per store?
select * from sales_revenue;

select store_location, avg(transaction_qty * unit_price) as 'Average transactions'
FROM sales_revenue
group by store_location
order by 'Average transactions';

